[build]
  publish = "dist/"
  command = "yarn lint && yarn format && yarn build"
  #functions = "functions/"

[context.production]
  publish = "dist/"
  command = "yarn lint && yarn format && yarn build"
  environment = { NODE_VERSION = "18" }
